### ISSUE TITLE
introduction.html vs introductions.html vs ...

### ISSUE THREAD

**Issue by mariusandra** [railsgirls-be/railsgirls_guide#12]
We had a confusion with `introduction.html` vs `introductions.html`.

The guide says to create a file called `introduction.html`, but then asks to move `introductions.html`. However one girl also created `introductions.html` in the beginning and then followed the other steps properly, while others renamed the `PagesController` action into `introduction`. All of this caused some small annoyances.

Might it be better to rename it to something simpler, like `me.html` or `homepage.html`?

**Comment by Bertg** [comment]
How about `index.html` or `home.html` ?

**Comment by alicetragedy** [comment]
@marius0 yep, we had the same problem.
