### ISSUE TITLE
Content for the second page

### ISSUE THREAD

**Issue by mariusandra** [railsgirls-be/railsgirls_guide#16]
Instead of `second_page` that then remains empty, how about adding something with a bit more meaning? Such as `favourite_books`, `videos`, `my_family` or `insert_name_of_hobby_here`?

Perhaps some made a nicer page, but in my team everyone made `second_page` that was then linked to from the header, but otherwise lacked a reason to exist.

**Comment by Bertg** [comment]
The second page could maybe be the site @wrtsprt suggested. A page with a "stories", "recipes", "posts" or whatever. That gives us a means to also make the 2nd page in the "HTML"-only part of the guide. 

I had my girls asking about links, and a second page is a great way of doing that.

**Comment by wrtsprt** [comment]
#23 adds to that.

**Comment by wrtsprt** [comment]
@bert can you elaborate on what you mean by e.g. stories?

**Comment by Bertg** [comment]
It was your initial idea :) I think stories where just an alternative name for "posts".

**Comment by wrtsprt** [comment]
OK cool. Yeah maybe something that could eventually become a blog could be nice. so for advanced students we can go a hell of a lot further and have a real domain that everyone gets, to work with. And the first page could be the about page. According to me that is a great idea! This would clarify why we're doing all this and give it a nice frame.

**Comment by wrtsprt** [comment]
I think #36 is again the same idea, and we'll try to follow up in that one.
