### ISSUE TITLE
Upgrade guide to Rails 5 syntax

### ISSUE THREAD

**Issue by wrtsprt** [railsgirls-be/railsgirls_guide#39]
One of the big confusions for students is the `rake` vs. `rails` thing. When do I type which. In rails 5 that is solved and we should ASAP move to using only that. We would remove one more change to loose students along the way. 

I am wondering if after the install party yesterday everyone was on Rails 5 by default? Could there be a case that a student has to work with Rails 4? Only in that case removing the `rake` would be a problem.

**Comment by otagi** [comment]
Done in e950ee4.
