### ISSUE TITLE
How cheeky should the language be in our guide? 

### ISSUE THREAD

**Issue by wrtsprt** [railsgirls-be/railsgirls_guide#43]
`[...] because editing your code every time you learn a new language is for amateurs.`

Should we keep this kind jokes in our guide?

**Comment by wrtsprt** [comment]
@borisrorsvort says: I get the funny tone but «is for amateurs» is not very inclusive.

**Comment by borisrorsvort** [comment]
It can be cheeky but we should maybe avoid to refer to pro practices like that for people that just started. Since they actually are amateurs, it might be misplaced. You can just say what you meant without judgments about levels.

**Comment by wrtsprt** [comment]
Agreed.
