### ISSUE TITLE
Improve commands where introductions.html is moved into public folder. 

### ISSUE THREAD

**Issue by wrtsprt** [railsgirls-be/railsgirls_guide#7]
The pseudo code is not understandable. Ideally we stick to the convention of making one file with in a predictable directory, so we can add a copy-pastable move command to the guide.

**Comment by otagi** [comment]
I wonder if moving `introductions.html` to the `public` folder is not too confusing, as it's only a temporary step, and seldom used in a real app. 

Would it be more straightforward to explain the Rails layout and views first, and then copy-paste the HTML code into them, skipping the `public` step?

**Comment by mariusandra** [comment]
What I liked about this step is that it shows them a transition from something where the browser says "file:///Users/me/Desktop/railsgirls/introductions.html" into something where it starts with a "http://" with the minimal amount of changes. Then the coach can explain how computers on the internet (servers) are no different from the same computer you're using now - a potentially eye opening "I can do this" moment for some people.

That said, it might be better to skip the public folder step and copy the full file directly into a /views/pages/*.html.erb "embedded ruby" file instead.

I would not introduce layouts at this point, but only when they create their second file.

**Comment by Bertg** [comment]
:+1: On skipping the `/public` step in the guide.

**Comment by wrtsprt** [comment]
I think keeping the `/public` step will help not overwhelming the students. You have to do all the controller generation stuff until you can see the result of the move otherwise. I'd suggest to keep this step in. So let's in this issue focus on improving the actual move commands. 

I will create another issue with the point that @mariusandra made, since he's right, the big point after moving the file to public is the change in the URL. So we should explicitly mention that, which we don't. (https://github.com/railsgirls-be/railsgirls_guide/issues/19)

**Comment by wrtsprt** [comment]
obsolete after https://github.com/brug-be/railsgirls_guide/pull/42
